[tool.ruff]
# Ajusta si usas otra versión base
target-version = "py311"
[tool.ruff.lint]
# Reglas por defecto (E*, F*) + "I" para ordenar imports (isort)
select = [
"E4","E7","E9", # pycodestyle (errores)
"F", # Pyflakes (errores comunes)
"I", # isort (ordenar imports)
"B", # flake8-bugbear (buenas prácticas)
"UP" # pyupgrade (moderniza sintaxis)
]
# Ignora lo que prefieras (ejemplo: no marcar líneas largas)
# ignore = ["E501"]
fixable = ["ALL"]
[tool.ruff.format]
# Estilo tipo Black por defecto (comillas dobles, etc.)
# Puedes añadir preferencias aquí si lo necesitas