name: CI Ruff

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - name: Lint con Ruff
      uses: astral-sh/ruff-action@v3
      with:
        args: "check --fix"
