SUPABASE_URL = "https://qlricjadlkoquyfucslp.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFscmljamFkbGtvcXV5ZnVjc2xwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEwNTQxMjAsImV4cCI6MjA3NjYzMDEyMH0.Io9XDrWT9m2AbMdtqHCn6Dm3vcB2QoRtHYZW8JwDkP0"
